database/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.Models
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Product
    {
       
        public int Id { get; set; }
        
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Category Category { get; set; }
    }
}

database/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using database.Models;

namespace database.Controllers
{
    public class CartsController : Controller
    {
        private StoreeEntities1 db = new StoreeEntities1();

        // GET: Carts
        public ActionResult Index()
        {
            var carts = db.Carts.Include(c => c.Product);
            return View(carts.ToList());
        }

        // GET: Carts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // GET: Carts/Create
        public ActionResult Create()
        {
            ViewBag.product_id = new SelectList(db.Products, "Id", "name");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "product_id,added_at")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Carts.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.product_id = new SelectList(db.Products, "Id", "name", cart.product_id);
            return View(cart);
        }

        // GET: Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            ViewBag.product_id = new SelectList(db.Products, "Id", "name", cart.product_id);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "product_id,added_at")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.product_id = new SelectList(db.Products, "Id", "name", cart.product_id);
            return View(cart);
        }

        // GET: Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cart cart = db.Carts.Find(id);
            db.Carts.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        //public ActionResult orderNow(int id)
        //{
        //    if(Session["cart_session"] == null)
        //    {
        //        List<Product> cart_session = new List<Product>();
        //        cart_session.Add(new Item(db.Products.Find(id)));

        //         Session["cart_session"] = cart_session;
        //     }
        //    else
        //    {

        //    }
        //    return View("cart");
        //}



    }
}

database/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using database.Models;
using System.IO;




namespace database.Controllers
{
    public class ProductsController : Controller
    {
        public StoreeEntities1 db = new StoreeEntities1();

        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Cart).Include(p => p.Category);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.Id = new SelectList(db.Carts, "product_id", "product_id");
            ViewBag.category_id = new SelectList(db.Categories, "id", "name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,name,price,image,description,category_id")] Product product, HttpPostedFileBase imgfile)
        {
            if (ModelState.IsValid)
            {
                String path = "";
                if(imgfile.FileName.Length > 0)
                {
                    path = "~/images/" + Path.GetFileName(imgfile.FileName);
                    imgfile.SaveAs(Server.MapPath(path));
                }
                product.image = path ;
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id = new SelectList(db.Carts, "product_id", "product_id", product.Id);
            ViewBag.category_id = new SelectList(db.Categories, "id", "name", product.category_id);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id = new SelectList(db.Carts, "product_id", "product_id", product.Id);
            ViewBag.category_id = new SelectList(db.Categories, "id", "name", product.category_id);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,name,price,image,description,category_id")] Product product, HttpPostedFileBase imagefile)
        {
            if (ModelState.IsValid)
            {
                String path = "";
                if (imagefile.FileName.Length > 0)
                {
                    path = "~/images/" + Path.GetFileName(imagefile.FileName);
                    imagefile.SaveAs(Server.MapPath(path));
                }
                product.image = path;
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id = new SelectList(db.Carts, "product_id", "product_id", product.Id);
            ViewBag.category_id = new SelectList(db.Categories, "id", "name", product.category_id);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Add_Cart()
        {
            return View();
        }
        public ActionResult Products(string searching)
        {

            
            var cat = from s in db.Products
                select s;
            if(!string.IsNullOrEmpty(searching))
            {
                cat = cat.Where(s => s.Category.name.Contains(searching));
            }

            return View(cat.ToList());
        }

        public ActionResult homePage()
        {
            var recs = db.Products.ToList();

            return View(recs);
        }
        public ActionResult view_details(string searching_details)
        {
            //var det = db.Products.ToList();

            //return View(det);
            var det = from s in db.Products
                      select s;
            if (!string.IsNullOrEmpty(searching_details))
            {
                det = det.Where(s => s.name.Contains(searching_details));
            }

            return View(det.ToList());
        }
        
        public ActionResult Add_toCart(int id)
        {

            List<Item> session_add = new List<Item>();
            var bb = db.Products.Find(id);
            session_add.Add(new Item()
            {
                product = bb,
               
            });
            Session["session_add"] = session_add;

            return View();
        }
        public ActionResult Remove_FromCart(int id)
        {
            List<Item> session_add = (List<Item>)Session["session_add"];
            foreach (var item in session_add)
            {
                if (item.product.Id == id)
                {
                    session_add.Remove(item);
                    break;
                }
            }
            Session["session_add"] = session_add;
            return Redirect("Products");
            
        }
    }
}

database/Views/Products/Add_Cart.cshtml
@model IEnumerable<database.Models.Product>

@using database.Controllers
@using database.Models

@{
    ViewBag.Title = "Add_toCart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Shopping Cart</h2>


<table class="table">
    <tr>
        <th>Product Name</th>
        <th>Price</th>
        <th>Product ID</th>
        <th>Added At</th>

    </tr>

    

</table>

database/Views/Products/Add_toCart.cshtml
@model IEnumerable<database.Models.Product>
@using database.Controllers
@using database.Models

@{
    ViewBag.Title = "Add_toCart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Shopping Cart</h2>


<table class="table">
    <tr>
        <th>Product Name</th>
        <th>Price</th>
        <th>Product ID</th>
        <th>Added At</th>

    </tr>

    @if (Session["session_add"] != null)
    {
        foreach (Item item in (List<Item>)Session["session_add"])
        {
            <tr>
                <th>@item.product.name</th>
                <th>@item.product.price</th>
                <th>@item.product.Id</th>
                <th>@item.product.Cart.added_at</th>
                <th>
                    @using (Html.BeginForm("Remove_FromCar", "Products",new {id=item.product.Id }, FormMethod.Post))
                    {
                        <a href="@Url.Action("Remove_FromCar","Products")">
                            <input type="submit" value="Remove" class="btn btn-danger"  style="width:100%" />
                        </a>
                    }
                </th>

            </tr>

        }
    }

</table>

database/Views/Products/Create.cshtml
@model database.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Product",FormMethod.Post,new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" id="imgfile" name="imgfile" class="form-control"/>
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

database/Views/Products/Delete.cshtml
@model database.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cart.product_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cart.product_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
           
        </div>
    }
</div>

database/Views/Products/Details.cshtml
@model database.Models.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cart.product_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cart.product_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

database/Views/Products/Edit.cshtml
@model database.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
@using (Html.BeginForm("Edit","Product",FormMethod.Post,new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="imagefile" name="imagefile" class="form-control" />
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

database/Views/Products/Index.cshtml
@model IEnumerable<database.Models.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>

    @Html.ActionLink("New Product", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cart.product_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.price)
        </td>
        <td>
           <img src="@Url.Content(item.image)" width="50" height="50"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cart.product_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id },new {@class="btn btn-info" }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id },new {@class="btn btn-primary" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id },new {@class="btn btn-danger" })
        </td>
    </tr>
}

</table>

database/Views/Products/Products.cshtml
@model IEnumerable<database.Models.Product>
@using database.Models
@using database.Controllers

@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Products</h2>
<p>

    @Html.ActionLink("New Product", "Create", null, new { @class = "btn btn-ınfo" })
</p>

<p>
    @{

        if (Session["session_add"] != null)
        {

            foreach (Item item in (List<Item>)Session["session_add"])
            {
                using (Html.BeginForm("Add_toCart", "Products",  new {id=item.product.Id } ,FormMethod.Post))
                {
                    <a href="@Url.Action("Add_toCart", "Products", new { id = item.product.Id })">
                        <input type="submit" value="Cart" class="pull-right" />
                    </a>

                }
            }
        }
    }
</p>




<p>
    Categories which valid in website ( phone , labtobs , tablets , TV , AirPods )
</p>



@using (Html.BeginForm("Products", "Products", FormMethod.Get))
{
    @Html.TextBox("searching")
    <input type="submit" class="btn btn-info" value="Search" />
}
<hr />

@foreach (var item in Model)
{

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="@Url.Content(item.image)" width="242" height="200">
            <div class="caption">
                <h3>@item.name</h3>

                <p>@item.price</p>
                @using (Html.BeginForm("Add_toCart", "Products", new { id = item.Id }, FormMethod.Post))
                {
                    <a href="@Url.Action("Add_toCart","Products")">
                        <input type="submit" value="Add To Cart" class="btn btn-danger" @*onclick="location.href='@Url.Action("Create", "Carts", new { id = item.id })'"*@ style="width:100%" />
                    </a>
                }


                @using (Html.BeginForm("view_details", "Products", FormMethod.Post))
                {
                    <a href="@Url.Action("view_details","Products")">
                        <input type="submit" value="Show Details" class="btn btn-primary" @*onclick="location.href='@Url.Action("Create", "Carts", new { id = item.id })'"*@ style="width:100%" />
                    </a>
                }
            </div>
        </div>
    </div>
}


@*--------------------------------------------------footer--------------------------------*@

<html>

<head>

</head>
<style>
    .footer {
        background: #303036;
        color: #d3d3d3;
        height: 500px;
        position: relative;
        margin-top: 30px;
        float: left;
        width: 100%;
        display: inline;
    }

    .footer_bottom {
        background: #343a40;
        color: #686868;
        height: 50px;
        width: 100%;
        text-align: center;
        position: absolute;
        bottom: 0px;
        left: 0px;
        padding-top: 20px;
        k
    }

    .bord {
        float: left;
    }

    .contact {
        float: right;
        width: 50%;
        height: 500px;
    }

    .input1 {
        display: block;
        width: 350px;
        height: 40px;
        margin-top: 20px;
        background: #ECE0E0;
    }

    .texterea1 {
        display: block;
        width: 400px;
        height: 80px;
        margin-top: 30px;
        background: #ECE0E0;
    }

    .logo-text {
        color: #05f7ff;
        margin-left: 20px;
    }

    span.title2 {
        color: white;
    }

    .big {
        width: 120px;
        height: 30px;
        color: white;
        font-size: 16px;
        font-weight: bold;
        margin-top: 50px;
        background: green;
    }

    .contact_us {
        color: #05f7ff;
        font-weight: bold;
        font-size: 30px;
        margin-top: 50px;
    }

    .par {
        margin-left: 20px;
    }

    .icons {
        margin-left: 20px;
        margin-top: 20px;
    }
</style>
<body>
    <div class="footer">
        <div class="bord">
            <div class="footer_section about">
                <h1 class="logo-text"><span class="title2">Onlıne</span>Shoppıng</h1>
                <p class="par">
                    Consumers find a product of interest by visiting the website of<br />
                    the retailer directly or by searching among alternative vendors <br />
                    using a shopping search engine.Once a particular product has been<br />
                    found on the website of the seller, most online retailers use<br />
                    shopping cart software
                </p>
                <div class="icons">
                    <span><i class="fa-phone"></i> &nbsp; 123-45-789</span>
                    <br>
                    <span><i class="fa-envelope"></i> &nbsp; info@awainspires.com</span>

                </div>
            </div>
        </div>
        <div class="contact">
            <h2 class="contact_us"> Contact <span class="title2">Us</span></h2>
            <br>
            <form action="index.html" method="post">
                <input type="email" name="email" class="input1" placeholder="Your email address...">
                <textarea name="message" class="texterea1" placeholder="Your message..."></textarea>
                <button type="submit" class="big">
                    <i class="fas fa-envelope"></i>
                    Send
                </button>
            </form>
        </div>
        <div class="footer_bottom">
            &copy;Codingpoets.com/Designed by Awa Melvine
        </div>


</body>
</html>

database/Views/Products/view_details.cshtml
@model IEnumerable<database.Models.Product>

@{
    ViewBag.Title = "view_details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>view_details</h2>




@foreach (var item in Model)
{

        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <h3>@item.name  @item.price  ( @item.Category.name )</h3>
                <img src="@Url.Content(item.image)" alt="..." width="242" height="200">
                <div class="caption">
                    <p>@item.description</p>

                        @Html.ActionLink("Update", "Edit", new { id = item.Id }, new { @class = "btn btn-info" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })





                 </div>
             </div>
         </div>


}